#!/usr/bin/env bash
# Install nginx web server unto a server

sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
