#!/usr/bin/env bash
# Create a file containing it's PID. The script
# also handles the SIGTERM AND SIGINT signals

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid;exit' 15
trap '"Y U no love me?!"' 2
echo $$ > /var/run/myscript.pid

for (( ; ; ));
do
	echo "Infinity and beyond";
done;
