#!/usr/bin/env bash
# Manages a process

state=$1

start_proc() {
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
}

stop_proc() {
	kill "$(pgrep -f /manage_my_process)"
	rm /var/run/my_process.pid
}

case "$state" in
	"start")
		start_proc
		echo "manage_my_process started"
		;;
	"stop")
		stop_proc
		echo "manage_my_process stopped"
		;;
	"restart")
		stop_proc
		start_proc
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
