#!/usr/bin/env bash
# Prints numbers ranging from 1 through 100
# printing Fizz, Buzz and FizzBuzz when needed

index=1
times_to_print=100

for ((; index <= times_to_print; index++));
do
	if (("$index" % 3 == 0 && "$index" % 5 == 0))
	then
		echo "FizzBuzz"
	elif (("$index" % 3 == 0))
	then
		echo "Fizz"
	elif (("$index" % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$index";
	fi
done;
