#!/usr/bin/env bash
# Print Best School 10 times but bad luck and good
# luck on the 4th and 8th iteration respectively

text="Best School"
times_to_print=10
index=0

while (("$index" < "$times_to_print"));
do
	if (("$index" == 3))
	then
		echo "bad luck"
	elif (("$index" == 7))
	then
		echo "good luck"
	else
		echo "$text"
	fi
	index=$((index + 1));
done;
