#!/usr/bin/env bash
# Prints every minute in the first 12 hours

hour=0
minute=1

while (("$hour" <= 12));
do
	echo "Hour: $hour"
	minute=1

	while (("$minute" < 60));
	do
		echo "$minute"
		minute=$((minute + 1));
	done;

	hour=$((hour + 1));
done
