#!/usr/bin/env bash
# Configure nginx to listen on port 8080 as the user nginx
pkill apache2
sudo sed -i 's/www-data/nginx/' /etc/nginx/nginx.conf
chmod 666 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
